# Generated by Django 4.2.6 on 2024-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packageName', models.CharField(max_length=255)),
                ('testDescription', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packageCategory', models.CharField(max_length=255)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discountTag', models.BooleanField(default=False)),
                ('listOfTest', models.JSONField()),
                ('selected', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
