# Generated by Django 5.0.2 on 2024-02-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='testDescription',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
